import { conversations, missingDocumentChecklists, requiredDocumentRules } from "@/lib/data";
import { loanApplicationRepository } from "@/lib/repositories/loan-applications";
import type {
  AgentActionLog,
  Conversation,
  LoanApplication,
  MissingDocumentChecklistItem,
  RequiredDocumentRule
} from "@/lib/types";

export type AgentReviewResult = {
  application: LoanApplication;
  rules: RequiredDocumentRule[];
  checklist: MissingDocumentChecklistItem[];
  draftMessage: Conversation["messages"][number];
  actionLogs: AgentActionLog[];
};

export async function runMissingDocumentAnalysis(applicationId: string): Promise<AgentReviewResult | undefined> {
  const application = await loanApplicationRepository.findById(applicationId);

  if (!application) {
    return undefined;
  }

  const rules = getRequiredRulesForApplication(application);
  const uploadedTypes = new Set(application.documents.map((document) => document.documentType));
  const checklist = rules.map((rule) => ({
    id: `generated-${application.id}-${rule.id}`,
    loanApplicationId: application.id,
    requiredDocumentRuleId: rule.id,
    documentType: rule.documentType,
    label: rule.label,
    isSatisfied: uploadedTypes.has(rule.documentType),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }));
  const missingLabels = checklist.filter((item) => !item.isSatisfied).map((item) => item.label);
  const draftMessage = {
    id: `draft-${application.id}`,
    conversationId: `conversation-${application.id}`,
    author: application.assignedOfficer,
    direction: "OUTBOUND" as const,
    status: "PENDING_APPROVAL" as const,
    subject: `Missing documents for ${application.applicationNumber}`,
    body: buildBorrowerFollowUp(application, missingLabels),
    createdAt: new Date().toISOString()
  };
  const actionLogs: AgentActionLog[] = [
    {
      id: `log-${application.id}-inspect`,
      loanApplicationId: application.id,
      actionType: "INSPECT_APPLICATION",
      actor: application.assignedOfficer,
      outputSummary: "Agent inspected borrower profile, loan request, uploaded documents, and existing review notes.",
      createdAt: new Date().toISOString()
    },
    {
      id: `log-${application.id}-checklist`,
      loanApplicationId: application.id,
      actionType: "GENERATE_CHECKLIST",
      actor: application.assignedOfficer,
      outputSummary: `Agent generated ${checklist.length} checklist items with ${missingLabels.length} missing.`,
      createdAt: new Date().toISOString()
    },
    {
      id: `log-${application.id}-draft`,
      loanApplicationId: application.id,
      actionType: "DRAFT_BORROWER_MESSAGE",
      actor: application.assignedOfficer,
      outputSummary: "Agent drafted a borrower follow-up message and left it pending officer approval.",
      createdAt: new Date().toISOString()
    },
    {
      id: `log-${application.id}-note`,
      loanApplicationId: application.id,
      actionType: "CREATE_INTERNAL_NOTE",
      actor: application.assignedOfficer,
      outputSummary: "Agent drafted an internal note summarizing missing document follow-up.",
      createdAt: new Date().toISOString()
    },
    {
      id: `log-${application.id}-approval`,
      loanApplicationId: application.id,
      actionType: "CREATE_APPROVAL_REQUEST",
      actor: application.assignedOfficer,
      outputSummary: "Agent created an officer approval request for the borrower-facing draft.",
      createdAt: new Date().toISOString()
    }
  ];

  return {
    application,
    rules,
    checklist,
    draftMessage,
    actionLogs
  };
}

export function getRequiredRulesForApplication(application: LoanApplication) {
  return requiredDocumentRules.filter(
    (rule) =>
      rule.loanType === application.loanType &&
      rule.borrowerType === application.borrowerProfile.borrowerType &&
      rule.isRequired
  );
}

export function getStoredChecklist(applicationId: string) {
  return missingDocumentChecklists.filter((item) => item.loanApplicationId === applicationId);
}

export function getConversationsForApplication(applicationId: string) {
  return conversations.filter((conversation) => conversation.loanApplicationId === applicationId);
}

function buildBorrowerFollowUp(application: LoanApplication, missingLabels: string[]) {
  const borrowerName = application.borrowerProfile.legalName;
  const missingText = missingLabels.length > 0 ? missingLabels.join(", ") : "no additional documents required";

  return `Dear ${borrowerName},\n\nWe have received your loan application ${application.applicationNumber}. To continue with your review, please provide the following documents: ${missingText}.\n\nThis is a draft generated by Obraims Agent and will only be sent after review by a loan officer. This message is not a commitment to approve your loan.\n\nKind regards,\n${application.assignedOfficer?.name ?? "Your lending team"}`;
}
